### ISSUE TITLE
update `.gitignore`

### ISSUE THREAD

**Issue by mfklauberg** [mfklauberg/time#23]
update `.gitignore` to also include `package-lock.json` and `yarn.lock`

**Comment by LuisEvilCo** [comment]
I would like to take this one :)

**Comment by mfklauberg** [comment]
hey @LuisEvilCo, @herberttn already opened a PR for that, but thanks for the offer!

**Comment by damoonrashidi** [comment]
imo it's good practice to include the lock-files in the repo to ensure that all the versions for dependencies and third party dependencies are synced between contributors and build steps.
